changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts}"

enableMessageNames: false

enableStrictSsl: false

nodeLinker: pnp

npmAuditRegistry: "https://npm.pkg.github.com"

npmAuthToken: $NPM_TOKEN

npmPublishRegistry: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpEnableEsmLoader: true

pnpFallbackMode: dependencies-only

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.1.cjs
